bookers2-debug-main/config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update ]do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update]
 
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  
  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

bookers2-debug-main/app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

bookers2-debug-main/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.build(book_comment_params)
    @book_comment.book_id = @book.id
    @book_comment.save
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    @book_comment=BookComment.find_by(id: params[:id], book_id: params[:book_id])
    @book_comment.destroy
    @book_comment = BookComment.new
  end
  
 

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

bookers2-debug-main/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

bookers2-debug-main/app/views/book_comments/_comment.html.erb
<table class='table' style='border-collapse: collapse;'>
<% book.book_comments.each do |book_comment| %>
    <tr style='border: none;'>
      <td style='border: none; padding: 5px;'>
        <%= link_to(book.user) do %>
      <%= image_tag book.user.get_profile_image, size:"50x50" %><br>
      <%= book.user.name %>
      <% end %>
      </td>
      <td style='border: none; padding: 5px;'>
        <p><%= book_comment.comment %></p>
      </td>
      <td style='border: none'>
        <% if book_comment.user == current_user %>
          <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn btn-danger" %>
        <% end %>
      </td>
      <td style='border: none'></td>
      <td style='border: none'></td>
      <td style='border: none'></td>
      <td style='border: none'></td>
    </tr>
  <% end %>
</table>

<div>
<%= form_with(model: [book, book_comment], local: false) do |f| %>
    <div class="row">
      <div class="col-md-12">
        <%= f.text_area :comment, rows: '8', placeholder: "コメントをここに", class: "form-control" %>
      </div>
    </div>
    <div class="row mt-2">
      <div class="col-md-12">
        <%= f.submit "送信する", class: "btn btn-secondary" %>
      </div>
    </div>
  <% end %>
</div>

bookers2-debug-main/app/views/book_comments/create.js.erb
$("#comments-area").html("<%= j(render 'book_comments/comment', book: @book,book_comment: @book_comment) %>")

bookers2-debug-main/app/views/book_comments/destroy.js.erb
$("#comments-area").html("<%= j(render 'book_comments/comment', book: @book,book_comment: @book_comment) %>")